# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_img', models.ImageField(upload_to='')),
                ('user_name', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_message',
            },
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_img', models.ImageField(upload_to='')),
                ('user_name', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Message')),
            ],
            options={
                'db_table': 'tb_message_reply',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_name', models.CharField(max_length=32, null=True)),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('passwd', models.CharField(max_length=32)),
                ('sex', models.IntegerField(default=1)),
                ('phone', models.CharField(max_length=11, null=True, unique=True)),
                ('birth', models.DateTimeField()),
                ('position', models.CharField(max_length=128)),
                ('likes', models.CharField(max_length=64, null=True)),
                ('head_img', models.ImageField(null=True, upload_to='')),
                ('user_tag', models.CharField(max_length=64, null=True)),
                ('abstract', models.CharField(max_length=128, null=True)),
                ('qq_num', models.CharField(max_length=32, null=True, unique=True)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('weibo', models.CharField(max_length=32, null=True, unique=True)),
                ('git_name', models.CharField(max_length=32, null=True, unique=True)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=64)),
                ('img', models.ImageField(upload_to='')),
                ('web_url', models.CharField(max_length=32)),
                ('abstract', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'tb_web_info',
            },
        ),
    ]
