# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'tb_article_tag',
            },
        ),
        migrations.CreateModel(
            name='MyArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=32)),
                ('abstract', models.CharField(max_length=128)),
                ('article', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('count_of_read', models.IntegerField(default=0, null=True)),
                ('count_of_comment', models.IntegerField(default=0, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleTag')),
            ],
            options={
                'db_table': 'tb_article',
            },
        ),
        migrations.CreateModel(
            name='ReaderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_name', models.CharField(max_length=32)),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('head_img', models.CharField(max_length=128)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.MyArticle')),
            ],
            options={
                'db_table': 'tb_reader_comment',
            },
        ),
    ]
